apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: iflow-monitor
spec:
  ports:
    - port: 8428
      name: vm
    - port: 9090
      name: ui
  selector:
    app: victoria-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: iflow-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: vm
          image: docker.m.daocloud.io/victoriametrics/victoria-metrics:v1.102.0
          args:
            - -storageDataPath=/vm-data
            - -httpListenAddr=0.0.0.0:8428
            - -prometheusListenAddr=0.0.0.0:9090
          ports:
            - containerPort: 8428
            - containerPort: 9090
          volumeMounts:
            - name: vm-data
              mountPath: /vm-data
      volumes:
        - name: vm-data
          emptyDir: {}
